"""Reusable deterministic layout engines for text-art note styles."""

from .hierarchy import FlatNode, HierarchyFacts, analyze_hierarchy, flatten_hierarchy
from .chain import ChainEntry, MeasuredChainEntry, measure_chain, paginate_chain
from .grid import (
    Column,
    GridRow,
    MeasuredRow,
    ShelfItem,
    ShelfPlacement,
    allocate_toward_demands,
    allocate_weighted,
    allocate_widths,
    pack_row_major,
    render_table,
)
from .axis import AxisPoint, AxisRange, QuantizedGroup, QuantizedPoint, quantize, quantize_points, round_half_up
from .lanes import LaneBand, LaneItem, allocate_lane_widths, lane_positions, synchronized_bands
from .evidence_pair import (
    Pair,
    ResolvedAnchor,
    SourceAnchor,
    SourceSlice,
    allocate_pair_widths,
    measure_pairs,
    measure_pairs_at_widths,
    pair_columns,
    resolve_source_anchors,
)
from .schema_blocks import Block, BlockPlacement, place_blocks, split_blocks
from .timeline import ScaledGap, ceil_scaled_cells, scale_gap
from .cluster import (
    ClusterItem,
    ClusterLayout,
    ClusterPlacement,
    ClusterSize,
    pack_shelves,
    rectangles_overlap,
)
from .radial import RadialEdge, RadialPlacement, RadialScene, RadialSize, layout_radial
from .flow import FlowArc, FlowLayout, FlowNode, FlowPlacement, layer_dag, place_flow

__all__ = [
    "Block",
    "BlockPlacement",
    "AxisPoint",
    "AxisRange",
    "Column",
    "ChainEntry",
    "FlatNode",
    "HierarchyFacts",
    "GridRow",
    "MeasuredRow",
    "MeasuredChainEntry",
    "LaneBand",
    "LaneItem",
    "Pair",
    "ResolvedAnchor",
    "ScaledGap",
    "SourceAnchor",
    "SourceSlice",
    "QuantizedGroup",
    "QuantizedPoint",
    "ShelfItem",
    "ShelfPlacement",
    "ClusterItem",
    "ClusterLayout",
    "ClusterPlacement",
    "ClusterSize",
    "RadialEdge",
    "RadialPlacement",
    "RadialScene",
    "RadialSize",
    "FlowArc",
    "FlowLayout",
    "FlowNode",
    "FlowPlacement",
    "analyze_hierarchy",
    "allocate_lane_widths",
    "allocate_pair_widths",
    "allocate_toward_demands",
    "allocate_weighted",
    "allocate_widths",
    "ceil_scaled_cells",
    "flatten_hierarchy",
    "measure_pairs",
    "measure_pairs_at_widths",
    "measure_chain",
    "lane_positions",
    "pack_row_major",
    "pack_shelves",
    "place_blocks",
    "paginate_chain",
    "pair_columns",
    "render_table",
    "resolve_source_anchors",
    "round_half_up",
    "quantize",
    "quantize_points",
    "split_blocks",
    "scale_gap",
    "rectangles_overlap",
    "layout_radial",
    "layer_dag",
    "place_flow",
    "synchronized_bands",
]
