#!/usr/bin/env python3
"""Generate the shared, frozen Unicode terminal-width contract.

The checked-in outputs are consumed at runtime. Regeneration is explicit so a
Python or libc Unicode database upgrade cannot silently change board geometry.
"""

from __future__ import annotations

import argparse
import unicodedata
from pathlib import Path
from typing import Callable


ROOT = Path(__file__).resolve().parents[1]
EXPECTED_UNICODE_VERSION = "16.0.0"
MAX_CODEPOINT = 0x10FFFF


def _ranges(predicate: Callable[[str, str], bool]) -> list[tuple[int, int]]:
    result: list[tuple[int, int]] = []
    begin: int | None = None
    previous = 0
    for codepoint in range(MAX_CODEPOINT + 1):
        character = chr(codepoint)
        category = unicodedata.category(character)
        matches = predicate(character, category)
        if matches and begin is None:
            begin = codepoint
        elif not matches and begin is not None:
            result.append((begin, previous))
            begin = None
        previous = codepoint
    if begin is not None:
        result.append((begin, MAX_CODEPOINT))
    return result


def _cpp_array(name: str, values: list[tuple[int, int]]) -> str:
    rows = "\n".join(
        f"    {{0x{first:06X}, 0x{last:06X}}}," for first, last in values
    )
    return f"inline constexpr UnicodeInterval {name}[] = {{\n{rows}\n}};\n"


def _python_array(name: str, values: list[tuple[int, int]]) -> str:
    rows = "\n".join(
        f"    (0x{first:06X}, 0x{last:06X})," for first, last in values
    )
    return f"{name}: tuple[tuple[int, int], ...] = (\n{rows}\n)\n"


def generate() -> tuple[str, str]:
    if unicodedata.unidata_version != EXPECTED_UNICODE_VERSION:
        raise SystemExit(
            "Unicode database mismatch: expected "
            f"{EXPECTED_UNICODE_VERSION}, got {unicodedata.unidata_version}"
        )

    marks = _ranges(lambda _character, category: category.startswith("M"))
    zero_width = _ranges(
        lambda character, category: bool(unicodedata.combining(character))
        or category in {"Mn", "Me"}
    )
    controls = _ranges(lambda _character, category: category.startswith("C"))
    wide = _ranges(
        lambda character, category: not category.startswith("C")
        and unicodedata.east_asian_width(character) in {"W", "F"}
    )
    whitespace = _ranges(lambda character, _category: character.isspace())

    header = f"""// Generated by tools/generate_unicode_width.py; do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

inline constexpr char kUnicodeContractVersion[] = \"{EXPECTED_UNICODE_VERSION}\";

struct UnicodeInterval {{
    char32_t first;
    char32_t last;
}};

template<std::size_t Size>
inline bool unicode_interval_contains(
    char32_t codepoint,
    const UnicodeInterval (&intervals)[Size]
) {{
    std::size_t first = 0;
    std::size_t last = Size;

    while (first < last) {{
        const std::size_t middle = first + (last - first) / 2;

        if (codepoint < intervals[middle].first) {{
            last = middle;
        }} else if (codepoint > intervals[middle].last) {{
            first = middle + 1;
        }} else {{
            return true;
        }}
    }}

    return false;
}}

"""
    header += _cpp_array("kUnicodeMarkIntervals", marks)
    header += "\n" + _cpp_array("kUnicodeZeroWidthIntervals", zero_width)
    header += "\n" + _cpp_array("kUnicodeControlIntervals", controls)
    header += "\n" + _cpp_array("kUnicodeWideIntervals", wide)
    header += "\n" + _cpp_array("kUnicodeWhitespaceIntervals", whitespace)

    module = f'''"""Generated Unicode {EXPECTED_UNICODE_VERSION} width tables; do not edit."""

from __future__ import annotations

UNICODE_CONTRACT_VERSION = "{EXPECTED_UNICODE_VERSION}"


def interval_contains(codepoint: int, intervals: tuple[tuple[int, int], ...]) -> bool:
    first = 0
    last = len(intervals)
    while first < last:
        middle = first + (last - first) // 2
        lower, upper = intervals[middle]
        if codepoint < lower:
            last = middle
        elif codepoint > upper:
            first = middle + 1
        else:
            return True
    return False

'''
    module += _python_array("MARK_INTERVALS", marks)
    module += "\n" + _python_array("ZERO_WIDTH_INTERVALS", zero_width)
    module += "\n" + _python_array("CONTROL_INTERVALS", controls)
    module += "\n" + _python_array("WIDE_INTERVALS", wide)
    module += "\n" + _python_array("WHITESPACE_INTERVALS", whitespace)
    return header, module


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    paths = (
        ROOT / "src" / "text" / "unicode_width_table.hpp",
        ROOT / "tools" / "textart_notes" / "core" / "unicode_width_table.py",
    )

    if arguments.check and unicodedata.unidata_version != EXPECTED_UNICODE_VERSION:
        marker = EXPECTED_UNICODE_VERSION
        stale = [
            path for path in paths
            if not path.is_file() or marker not in path.read_text(encoding="utf-8")
        ]
        if stale:
            for path in stale:
                print(f"missing generated Unicode {marker} table: {path.relative_to(ROOT)}")
            return 1
        return 0

    header, module = generate()
    outputs = dict(zip(paths, (header, module), strict=True))
    if arguments.check:
        stale = [path for path, content in outputs.items() if not path.is_file() or path.read_text() != content]
        if stale:
            for path in stale:
                print(f"stale generated file: {path.relative_to(ROOT)}")
            return 1
        return 0
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
