#!/usr/bin/env python3
"""Generate text-art, Agent-limit, and card-format contracts."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tools.textart_notes.core.contracts import (
    DEFAULT_AGENT_BOARD_PNG_SIDE,
    DEFAULT_AGENT_PNG_PIXELS,
    DEFAULT_AGENT_TIMEOUT_MILLISECONDS,
    MANIFEST_VERSION,
    MAX_AGENT_BOARD_PNG_SIDE,
    MAX_AGENT_HEADER_BYTES,
    MAX_AGENT_PNG_PIXELS,
    MAX_AGENT_QUERY_RESULTS,
    MAX_AGENT_REQUEST_BYTES,
    MAX_AGENT_RESPONSE_BYTES,
    MAX_MANIFEST_BYTES,
    MAX_MANIFEST_CARDS,
    MAX_RENDERER_INPUT_BYTES,
    MAX_TOTAL_PAYLOAD_BYTES,
    MIN_AGENT_BOARD_PNG_SIDE,
    MIN_AGENT_PNG_PIXELS,
)
from tools.textart_notes.core.models import GLOBAL_MAX_HEIGHT, GLOBAL_MAX_WIDTH


ROOT = Path(__file__).resolve().parents[1]
CARD_FORMATS_SOURCE = ROOT / "contracts" / "card-formats.json"
SCHEMA_PATH = ROOT / "tools" / "textart_notes" / "core" / "manifest.schema.json"
LIMITS_PATH = ROOT / "tools" / "textart_notes" / "core" / "protocol_limits.json"
CPP_LIMITS_PATH = ROOT / "src" / "generated" / "protocol_limits.hpp"
CPP_CARD_FORMATS_PATH = ROOT / "src" / "generated" / "card_formats.hpp"
PYTHON_CARD_FORMATS_PATH = ROOT / "tools" / "whiteboard_automation" / "generated_card_formats.py"


def encoded(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def schema() -> dict[str, object]:
    card = {
        "type": "object",
        "additionalProperties": False,
        "required": ["id", "format", "payload", "width", "height", "x", "y", "metadata"],
        "properties": {
            "id": {"type": "string", "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"},
            "format": {"const": "text-art"},
            "payload": {
                "type": "string",
                "pattern": "^generations/[0-9a-f]{64}/payloads/[a-z0-9]+(?:-[a-z0-9]+)*\\.txt$",
            },
            "width": {"type": "integer", "minimum": 1, "maximum": GLOBAL_MAX_WIDTH},
            "height": {"type": "integer", "minimum": 1, "maximum": GLOBAL_MAX_HEIGHT},
            "x": {"type": "integer", "minimum": 0, "maximum": 2**63 - 1},
            "y": {"type": "integer", "minimum": 0, "maximum": 2**63 - 1},
            "metadata": {"type": "object"},
        },
    }
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"https://whiteboard-tui.invalid/schema/textart-manifest-v{MANIFEST_VERSION}.json",
        "title": "whiteboardTUI text-art generation manifest",
        "type": "object",
        "additionalProperties": False,
        "required": ["manifest_version", "generation", "renderer", "theme", "cards"],
        "properties": {
            "manifest_version": {"const": MANIFEST_VERSION},
            "generation": {"type": "string", "pattern": "^[0-9a-f]{64}$"},
            "renderer": {"type": "string", "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"},
            "theme": {"enum": ["ascii", "unicode-light", "unicode-rich"]},
            "cards": {
                "type": "array",
                "minItems": 1,
                "maxItems": MAX_MANIFEST_CARDS,
                "items": card,
            },
        },
    }


def limits() -> dict[str, int]:
    return {
        "default_agent_board_png_side": DEFAULT_AGENT_BOARD_PNG_SIDE,
        "default_agent_png_pixels": DEFAULT_AGENT_PNG_PIXELS,
        "default_agent_timeout_milliseconds": DEFAULT_AGENT_TIMEOUT_MILLISECONDS,
        "manifest_version": MANIFEST_VERSION,
        "max_agent_board_png_side": MAX_AGENT_BOARD_PNG_SIDE,
        "max_agent_header_bytes": MAX_AGENT_HEADER_BYTES,
        "max_agent_png_pixels": MAX_AGENT_PNG_PIXELS,
        "max_agent_query_results": MAX_AGENT_QUERY_RESULTS,
        "max_agent_request_bytes": MAX_AGENT_REQUEST_BYTES,
        "max_agent_response_bytes": MAX_AGENT_RESPONSE_BYTES,
        "max_manifest_bytes": MAX_MANIFEST_BYTES,
        "max_manifest_cards": MAX_MANIFEST_CARDS,
        "max_renderer_input_bytes": MAX_RENDERER_INPUT_BYTES,
        "max_total_payload_bytes": MAX_TOTAL_PAYLOAD_BYTES,
        "min_agent_board_png_side": MIN_AGENT_BOARD_PNG_SIDE,
        "min_agent_png_pixels": MIN_AGENT_PNG_PIXELS,
    }


def cpp_limits() -> str:
    return f"""#pragma once

// Generated by tools/generate_contract_schema.py. Do not edit manually.
#include <cstddef>
#include <cstdint>

inline constexpr std::size_t kAgentHeaderLimit = {MAX_AGENT_HEADER_BYTES};
inline constexpr std::size_t kAgentTextLimit = {MAX_AGENT_REQUEST_BYTES};
inline constexpr std::size_t kAgentResponseLimit = {MAX_AGENT_RESPONSE_BYTES};
inline constexpr std::uint32_t kAgentQueryLimit = {MAX_AGENT_QUERY_RESULTS};
inline constexpr std::uint32_t kAgentPngDefaultPixels = {DEFAULT_AGENT_PNG_PIXELS};
inline constexpr std::uint32_t kAgentPngMinimumPixels = {MIN_AGENT_PNG_PIXELS};
inline constexpr std::uint32_t kAgentPngMaximumPixels = {MAX_AGENT_PNG_PIXELS};
inline constexpr std::uint32_t kAgentBoardPngDefaultSide = {DEFAULT_AGENT_BOARD_PNG_SIDE};
inline constexpr std::uint32_t kAgentBoardPngMinimumSide = {MIN_AGENT_BOARD_PNG_SIDE};
inline constexpr std::uint32_t kAgentBoardPngMaximumSide = {MAX_AGENT_BOARD_PNG_SIDE};
inline constexpr int kAgentDefaultTimeoutMilliseconds = {DEFAULT_AGENT_TIMEOUT_MILLISECONDS};
"""


def card_formats() -> tuple[dict[str, object], ...]:
    source = json.loads(CARD_FORMATS_SOURCE.read_text(encoding="utf-8"))
    if not isinstance(source, dict) or source.get("schema") != 1:
        raise ValueError("contracts/card-formats.json: schema must equal 1")
    raw_formats = source.get("formats")
    if not isinstance(raw_formats, list) or not raw_formats:
        raise ValueError("contracts/card-formats.json: formats must be a non-empty array")
    result: list[dict[str, object]] = []
    seen: set[str] = set()
    for index, item in enumerate(raw_formats):
        if not isinstance(item, dict) or set(item) != {"key", "minimum", "maximum", "save_format"}:
            raise ValueError(f"contracts/card-formats.json: invalid format at index {index}")
        key = item["key"]
        minimum = item["minimum"]
        maximum = item["maximum"]
        save_format = item["save_format"]
        if not isinstance(key, str) or not key or any(character not in "abcdefghijklmnopqrstuvwxyz-" for character in key):
            raise ValueError(f"contracts/card-formats.json: invalid key at index {index}")
        if key in seen:
            raise ValueError(f"contracts/card-formats.json: duplicate key {key}")
        seen.add(key)
        if (
            not isinstance(minimum, list)
            or not isinstance(maximum, list)
            or len(minimum) != 2
            or len(maximum) != 2
            or any(type(value) is not int for value in [*minimum, *maximum])
            or minimum[0] < 1
            or minimum[1] < 1
            or maximum[0] < minimum[0]
            or maximum[1] < minimum[1]
        ):
            raise ValueError(f"contracts/card-formats.json: invalid dimensions for {key}")
        if type(save_format) is not int or not 0 <= save_format <= 4:
            raise ValueError(f"contracts/card-formats.json: invalid save_format for {key}")
        result.append(item)
    return tuple(result)


def _contract_name(key: str) -> str:
    return "".join(word.capitalize() for word in key.split("-"))


def cpp_card_formats(formats: tuple[dict[str, object], ...]) -> str:
    rows = []
    for item in formats:
        minimum = item["minimum"]
        maximum = item["maximum"]
        assert isinstance(minimum, list) and isinstance(maximum, list)
        rows.append(
            f"inline constexpr GeneratedCardFormatContract kCardFormat{_contract_name(str(item['key']))}"
            f"{{{minimum[0]}, {minimum[1]}, {maximum[0]}, {maximum[1]}, {item['save_format']}}};"
        )
    return """#pragma once

// Generated by tools/generate_contract_schema.py. Do not edit manually.
#include <cstdint>

struct GeneratedCardFormatContract {
    std::int32_t minimum_width;
    std::int32_t minimum_height;
    std::int32_t maximum_width;
    std::int32_t maximum_height;
    std::uint8_t save_format;
};

""" + "\n".join(rows) + "\n"


def python_card_formats(formats: tuple[dict[str, object], ...]) -> str:
    payload = {
        str(item["key"]): {
            "minimum": item["minimum"],
            "maximum": item["maximum"],
        }
        for item in formats
    }
    return (
        '"""Generated card-format limits. Do not edit manually."""\n\n'
        "CARD_FORMATS = "
        + repr(payload)
        + "\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    formats = card_formats()
    outputs = {
        SCHEMA_PATH: encoded(schema()),
        LIMITS_PATH: encoded(limits()),
        CPP_LIMITS_PATH: cpp_limits(),
        CPP_CARD_FORMATS_PATH: cpp_card_formats(formats),
        PYTHON_CARD_FORMATS_PATH: python_card_formats(formats),
    }

    if arguments.check:
        stale = [path for path, content in outputs.items() if not path.is_file() or path.read_text(encoding="utf-8") != content]

        if stale:
            parser.error("generated contract is stale: " + ", ".join(str(path.relative_to(ROOT)) for path in stale))

        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
